# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 44298822729e9399d2d310798762232e6061848b5767b3abbfd200f903e39bc4f4437a8ff24485dbbd8ca78384981e7e4d450fa032318109c928edce882e2312
  jwt_secret: buerdnoispevnapoewih2983u102jdn20-f)(JH*&*^RFGVBHJsodub)
  jwt_expiration_hours: 24

test:
  secret_key_base: f4afc35e639ca0b0a4b9f182e078992c26266a4bd2b57a787754cabe36629c714e4aeff8a6d5488681b911550129de7d2ff7b52c20259c5fae4f589bbb348ac2
  jwt_secret: awiuflhaweiughbanwpivueobn293iutqn9w8gihvnawlieuhf028wehvoub
  jwt_expiration_hours: 6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: .`;N;zBGh%(3dss9gAXd{t@@f`Yrt.>/JFhM\UB2E@J/K84'Pz.9G)\m@]G<tJgK&,btkb
  jwt_expiration_hours: 24
